name: Cloud Run Deploy

on:
  push:
    branches:
      - master # not using

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.PROJECT_ID }}

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ vars.PROJECT_ID }}/${{ vars.IMAGE_NAME }} --project ${{ vars.PROJECT_ID }}
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image gcr.io/${{ vars.PROJECT_ID }}/${{ vars.IMAGE_NAME }} \
            --platform managed \
            --region ${{ vars.REGION }} \
            --allow-unauthenticated
