name: Cloud Run Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.PROVIDER }}
          service_account: 'https://challenges-ws2m6t2msa-uc.a.run.app'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'hello-cloud-run'
          image: 'gcr.io/cloudrun/hello'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
