name: Cloud Run Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-sa-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-sa-key.json
          gcloud auth configure-docker
          gcloud config set project ${{ vars.PROJECT_ID }}
          export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-sa-key.json
          export GOOGLE_CLOUD_PROJECT=${{ vars.PROJECT_ID }}

      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ vars.PROJECT_ID }}/${{ vars.IMAGE_NAME }}
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image gcr.io/${{ vars.PROJECT_ID }}/${{ vars.IMAGE_NAME }} \
            --platform managed \
            --region ${{ vars.REGION }} \
            --allow-unauthenticated
